let formConfig = {
  "config-one": [
    {
      name: "firstName",
      type: "text",
      required: true,
      label: "First Name",
      placeholder: "Enter your first name",
      message: "First Name is required",
      invalidMessage: "Invalid email address",
    },
    {
      name: "email",
      type: "email",
      label: "Email",
      model: {
        title: "Please select any one valid email",
        maxWidth: "md",
        name: "email",
        enable: true,
        path: "email",
      },
      required: true,
      minLength: 6,
      placeholder: "Enter your email",
      message: "Email is required",
      invalidMessage: "Invalid email address",
    },
    {
      name: "password",
      type: "password",
      label: "Password",
      minLength: 6,
      required: true,
      placeholder: "Enter your password",
      message: "Password is required",
      invalidMessage: "Password must be at least 6 characters",
    },
    {
      name: "age",
      type: "number",
      label: "Age",
      positive: true,
      integer: true,
      placeholder: "Enter your age",
      message: "age is required",
      invalidMessage: "Invalid email address",
    },
    {
      name: "gender",
      type: "radio",
      label: "Gender",
      required: true,
      source: {
        masterData: {
          path: "dclm.gender",
          valuePath: "code",
          labelPath: "name",
        },
        api: {
          url: "https://dummyjson.com/users",
          method: "GET",
          payload: {
            publicIdentifer: "{publicIdentifer}",
          },
          path: "users",
          valuePath: "id",
          labelPath: "firstName",
        },
      },
      options: [
        { value: "male", label: "Male" },
        { value: "female", label: "Female" },
      ],
      message: "Gender is required",
    },
    {
      name: "subscribe",
      type: "checkbox",
      oneOf: [true],
      label: "Subscribe to newsletter",
      message: "Subscribe is required",
      invalidMessage: "You must accept to subscribe",
    },
    {
      name: "country",
      type: "select",
      label: "Country",
      required: true,
      placeholder: "Select your country",
      options: [
        { value: "", label: "Select your country" },
        { value: "usa", label: "United States" },
        { value: "canada", label: "Canada" },
        { value: "uk", label: "United Kingdom" },
      ],
      message: "Country is required",
      invalidMessage: "Invalid email address",
    },
    {
      name: "hobbies",
      type: "multiselect",
      label: "Hobbies",
      minItems: 1,
      required: true,
      placeholder: "Select your hobbies",
      options: [
        { value: "reading", label: "Reading" },
        { value: "traveling", label: "Traveling" },
        { value: "gaming", label: "Gaming" },
        { value: "cooking", label: "Cooking" },
      ],
      message: "Hobbies is required",
      invalidMessage: "At least one hobby is required",
    },
  ],
  "config-two": [
    {
      name: "country",
      label: "Country",
      initialFetch: { url: "/api/countries" }, // Initial data fetching
    },
    {
      name: "state",
      label: "State",
      dependsOn: "country", // State depends on the selected country
      fetchUrl: (country) => `/api/states/${country}`,
    },
    {
      name: "city",
      label: "City",
      dependsOn: "state", // City depends on the selected state
      fetchUrl: (state) => `/api/cities/${state}`,
    },
  ],
  "config-three": [
    {
      name: "location",
      type: "select",
      label: "Location",
      required: true,
      placeholder: "Select your location",
      options: [
        { value: "", label: "Select your location" },
        { value: "usa", label: "United States" },
        { value: "canada", label: "Canada" },
        { value: "uk", label: "United Kingdom" },
      ],
      message: "Country is required",
      invalidMessage: "Invalid email address",
    },
    
    {
      name: "subSidiary",
      type: "select",
      label: "Sub Sidiary",
      required: true,
      placeholder: "Select your Sub Sidiary",
      options: [
        { value: "", label: "Select your Sub Sidiary" },
        { value: "usa", label: "United States" },
        { value: "canada", label: "Canada" },
        { value: "uk", label: "United Kingdom" },
      ],
      message: "Country is required",
      invalidMessage: "Invalid email address",
    },
    {
      name: "mobileNumber",
      type: "text",
      required: true,
      label: "Mobile Number",
      placeholder: "Enter your first name",
      message: "Mobile Number is required",
      invalidMessage: "Invalid mobile number address",
    },
    {
      name: "simNumber",
      type: "text",
      required: true,
      label: "Sim Number",
      placeholder: "Enter your first name",
      message: "Sim Number is required",
      invalidMessage: "Invalid mobile number address",
    },
  ],
  "config-four": [
    {
      name: "location",
      type: "select",
      label: "Location",
      required: true,
      placeholder: "Select your location",
      options: [
        { value: "", label: "Select your location" },
        { value: "usa", label: "United States" },
        { value: "canada", label: "Canada" },
        { value: "uk", label: "United Kingdom" },
      ],
      message: "Country is required",
      invalidMessage: "Invalid email address",
    },
    
    {
      name: "subSidiary",
      type: "select",
      label: "Sub Sidiary",
      required: true,
      placeholder: "Select your Sub Sidiary",
      options: [
        { value: "", label: "Select your Sub Sidiary" },
        { value: "usa", label: "United States" },
        { value: "canada", label: "Canada" },
        { value: "uk", label: "United Kingdom" },
      ],
      message: "Country is required",
      invalidMessage: "Invalid email address",
    },
      {
      name: "mobileNumber",
      type: "text",
      label: "Mobile Number",
      model: {
        title: "Please select any one valid Mobile Number",
        maxWidth: "md",
        name: "mobileNumber",
        enable: true,
        path: "mobileNumber",
      },
      required: true,
      minLength: 6,
      placeholder: "Enter your email",
      message: "Email is required",
      invalidMessage: "Invalid email address",
    },
    {
      name: "simNumber",
      type: "text",
      required: true,
      label: "Sim Number",
      placeholder: "Enter your first name",
      message: "Sim Number is required",
      invalidMessage: "Invalid mobile number address",
    },
  ],
};
export default formConfig;
